defaults:
  -  diffusion_model

device:  ${device}
parameter:
  training_loss_type: flow_matching
  lr: 1e-4
  imagesize: 64
  iterations: 200000
  numerworkers: 8
  batch_size: 50
  eval_freq: 10
  checkpoint_freq: 10
  dataset_path: /mnt/nfs3/zhangjinouwen/dataset/imagenet_2012
  checkpoint_path: /mnt/nfs3/zhangjinouwen/checkpoint/image
  video_save_path: ./video
  accelerate_checkpoint_path: ./data
  device: ${device}